//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dev_skb101.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class aluguel
    {
        public int id { get; set; }
        public int tipobike_id { get; set; }
        public int bicicleta_id { get; set; }
        [DisplayName("Retirada")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> dataEntrada { get; set; }

        [DataType(DataType.Date)]
        [DisplayName("Entrega")]
        public Nullable<System.DateTime> dataSaida { get; set; }
        public Nullable<bool> ativa { get; set; }
    
        public virtual bicicleta bicicleta { get; set; }
        public virtual tipobike tipobike { get; set; }
    }
}
