//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dev_skb101.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class bicicleta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bicicleta()
        {
            this.aluguel = new HashSet<aluguel>();
            this.revisao = new HashSet<revisao>();
        }

        public int id { get; set; }
        [DisplayName("Modelo")]
        public string nome { get; set; }
        [DisplayName("Descrição")]
        public string descricao { get; set; }
        [DisplayName("Disponibilidade")]
        public Nullable<bool> Alugada { get; set; }
        [DisplayName("Ativa")]
        public Nullable<bool> ativa { get; set; }
        [DisplayName("Número de Aluguel")]
        public Nullable<int> vezesAlugada { get; set; }
        public Nullable<int> codigo { get; set; }
        public string AlugadaString { get; set; }
        public string ativaString { get; set; }
        public Nullable<int> vendida { get; set; }
        public string vendidaString { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aluguel> aluguel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<revisao> revisao { get; set; }
    }
}
