//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dev_skb101.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sbk101dbEntities : DbContext
    {
        public sbk101dbEntities()
            : base("name=sbk101dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<aluguel> aluguel { get; set; }
        public virtual DbSet<bicicleta> bicicleta { get; set; }
        public virtual DbSet<revisao> revisao { get; set; }
        public virtual DbSet<tipobike> tipobike { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
