//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dev_skb101.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class revisao
    {
        public int id { get; set; }
        [DisplayName("Bicicleta")]
        public int bicicleta_id { get; set; }
        [DisplayName("Nome de quem Revisou")]
        public string autor { get; set; }
        [DisplayName("Quando a bike foi revisada")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> dataRevisao { get; set; }
        [DisplayName("Descrição")]
        public string descricao { get; set; }
        [DisplayName("Observação")]
        public string observacao { get; set; }

        [DataType(DataType.Date)]
        public DateTime dataFim { get; set; }

        public virtual bicicleta bicicleta { get; set; }
    }
}
