//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dev_skb101.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class usuario
    {
        public int id { get; set; }
        public string nome { get; set; }

        [DisplayName("Usuário")]
        [Required(ErrorMessage = "Campo Necessário")]
        public string login { get; set; }

        [DisplayName("Senha")]
        [Required(ErrorMessage = "Campo Necessário")]
        [DataType(DataType.Password)]
        public string senha { get; set; }

        [DisplayName("Tipo de Usuário")]
        public Nullable<bool> admin { get; set; }
        public string adminSaida { get; set; }
        public string LoginErrorMessage { get; set; }
    }
}
